liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~

        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [ 240, 180 ], mode: inset }