#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin_index:
  path: /admin
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: 'admin/index.html.twig'